USE SISTEMA_MARANATHA

--------------------------------------------------------- STOREPROCEDURES CATEGORIA ---------------------------------------------------------

-- PROCEDIMIENTO ALMACENADO BUSCAR CATEGORIA

CREATE PROC SP_BUSCARCATEGORIA
@BUSCAR NVARCHAR(20)
AS
SELECT * FROM CATEGORIA
WHERE NOMBRE LIKE @BUSCAR + '%'

-- PROCEDIMIENTO ALMACENADO INSERTAR CATEGORIA

CREATE PROC SP_INSERTARCATEGORIA
@NOMBRE NVARCHAR(20),
@DESCRIPCION NVARCHAR(256)
AS
INSERT INTO CATEGORIA VALUES (@NOMBRE, @DESCRIPCION)

-- PROCEDIMIENTO ALMACENADO EDITAR CATEGORIA

CREATE PROC SP_EDITARCATEGORIA
@IDCATEGORIA INT,
@NOMBRE NVARCHAR(30),
@DESCRIPCION NVARCHAR(256)
AS
UPDATE CATEGORIA SET NOMBRE = @NOMBRE, DESCRIPCION = @DESCRIPCION
WHERE IDCATEGORIA = @IDCATEGORIA

-- PROCEDIMIENTO ALMACENADO ELIMINAR CATEGORIA

CREATE PROC SP_ELIMINARCATEGORIA
@IDCATEGORIA INT
AS
DELETE CATEGORIA
WHERE IDCATEGORIA = @IDCATEGORIA

--------------------------------------------------------- STOREPROCEDURES MARCAS ---------------------------------------------------------


-- PROCEDIMIENTO ALMACENADO BUSCAR MARCA

CREATE PROC SP_BUSCARMARCA
@BUSCAR NVARCHAR(20)
AS
SELECT * FROM MARCA
WHERE NOMBRE LIKE @BUSCAR + '%'

-- PROCEDIMIENTO ALMACENADO INSERTAR MARCA

CREATE PROC SP_INSERTARMARCA
@NOMBRE NVARCHAR(20),
@DESCRIPCION NVARCHAR(256)
AS
INSERT INTO MARCA VALUES (@NOMBRE, @DESCRIPCION)

-- PROCEDIMIENTO ALMACENADO EDITAR MARCA

CREATE PROC SP_EDITARMARCA
@IDMARCA INT,
@NOMBRE NVARCHAR(30),
@DESCRIPCION NVARCHAR(256)
AS
UPDATE MARCA SET NOMBRE = @NOMBRE, DESCRIPCION = @DESCRIPCION
WHERE IDMARCA = @IDMARCA

-- PROCEDIMIENTO ALMACENADO ELIMINAR MARCA

CREATE PROC SP_ELIMINARMARCA
@IDMARCA INT
AS
DELETE MARCA
WHERE IDMARCA = @IDMARCA

--------------------------------------------------------- STOREPROCEDURES PRODUCTO ---------------------------------------------------------


-- PROCEDIMIENTO ALMACENADO BUSCAR PRODUCTO

CREATE PROC SP_BUSCARPRODUCTO
@BUSCAR NVARCHAR(20)
AS
SELECT * FROM PRODUCTO
WHERE PRODUCTO LIKE @BUSCAR + '%'

-- PROCEDIMIENTO ALMACENADO INSERTAR PRODUCTO

CREATE PROC SP_INSERTARPRODUCTO
@PRODUCTO NVARCHAR(50) NOT NULL,
@PRECIO_COMPRA DECIMAL (18,2) NULL,
@PRECIO_VENTA DECIMAL (18,2) NULL,
@STOCK INT NULL,
@IDCATEGORIA INT NOT NULL,
@IDMARCA INT NOT NULL
AS
INSERT INTO PRODUCTO VALUES (@PRODUCTO,@PRECIO_COMPRA,@PRECIO_VENTA,@STOCK,@IDCATEGORIA,@IDMARCA)

-- PROCEDIMIENTO ALMACENADO EDITAR PRODUCTO

CREATE PROC SP_EDITARPRODUCTO
@IDPRODUCTO INT,
@PRODUCTO NVARCHAR(50) NOT NULL,
@PRECIO_COMPRA DECIMAL (18,2) NULL,
@PRECIO_VENTA DECIMAL (18,2) NULL,
@STOCK INT NULL,
@IDCATEGORIA INT NOT NULL,
@IDMARCA INT NOT NULL
AS
UPDATE PRODUCTO SET PRODUCTO = @PRODUCTO, PRECIO_COMPRA = @PRECIO_COMPRA, PRECIO_VENTA = @PRECIO_VENTA, 
							STOCK = @STOCK, IDCATEGORIA = @IDCATEGORIA, IDMARCA = @IDMARCA
							WHERE IDPRODUCTO = @IDPRODUCTO

-- PROCEDIMIENTO ALMACENADO ELIMINAR PRODUCTO

CREATE PROC SP_ELIMINARPRODUCTO
@IDPRODUCTO INT
AS
DELETE PRODUCTO
WHERE IDPRODUCTO = @IDPRODUCTO

--------------------------------------------------------- STOREPROCEDURES ROL ---------------------------------------------------------


-- PROCEDIMIENTO ALMACENADO BUSCAR ROL

CREATE PROC SP_BUSCARROL
@BUSCAR NVARCHAR(20)
AS
SELECT * FROM ROL
WHERE ROL LIKE @BUSCAR + '%'

-- PROCEDIMIENTO ALMACENADO INSERTAR ROL

CREATE PROC SP_INSERTARROL
@ROL NVARCHAR(20)
AS
INSERT INTO ROL VALUES (@ROL)

-- PROCEDIMIENTO ALMACENADO EDITAR ROL

CREATE PROC SP_EDITARROL
@IDROL INT,
@ROL NVARCHAR(20)

AS
UPDATE ROL SET ROL = @ROL
WHERE IDROL = @IDROL

-- PROCEDIMIENTO ALMACENADO ELIMINAR ROL

CREATE PROC SP_ELIMINARROL
@IDROL INT
AS
DELETE ROL
WHERE IDROL = @IDROL

--------------------------------------------------------- STOREPROCEDURES EMPLEADO ---------------------------------------------------------


-- PROCEDIMIENTO ALMACENADO BUSCAR EMPLEADO

CREATE PROC SP_BUSCAREMPLEADO
@BUSCAR NVARCHAR(20)
AS
SELECT * FROM EMPLEADO
WHERE NOMBRE LIKE @BUSCAR + '%'

-- PROCEDIMIENTO ALMACENADO INSERTAR EMPLEADO

CREATE PROC SP_INSERTAREMPLEADO
@NOMBRE NVARCHAR(30),
@APELLIDO NVARCHAR(60),
@CEDULA VARCHAR(11),
@TELEFONO VARCHAR(10),
@DIRECION NVARCHAR(256) 
AS
INSERT INTO EMPLEADO VALUES (@NOMBRE, @APELLIDO, @CEDULA, @TELEFONO, @DIRECION)

-- PROCEDIMIENTO ALMACENADO EDITAR EMPLEADO

CREATE PROC SP_EDITAREMPLEADO
@IDEMPLEADO INT,
@NOMBRE NVARCHAR(30),
@APELLIDO NVARCHAR(60),
@CEDULA VARCHAR(11),
@TELEFONO VARCHAR(10),
@DIRECION NVARCHAR(256) 
AS
UPDATE EMPLEADO SET NOMBRE = @NOMBRE, APELLIDO = @APELLIDO, CEDULA = @CEDULA, TELEFONO = @TELEFONO, DIRECION = @DIRECION
WHERE IDEMPLEADO = @IDEMPLEADO

-- PROCEDIMIENTO ALMACENADO ELIMINAR EMPLEADO

CREATE PROC SP_ELIMINAREMPLEADO
@IDEMPLEADO INT
AS
DELETE EMPLEADO
WHERE IDEMPLEADO = @IDEMPLEADO

--------------------------------------------------------- STOREPROCEDURES USUARIO ---------------------------------------------------------


-- PROCEDIMIENTO ALMACENADO BUSCAR USUARIO

CREATE PROC SP_BUSCARUSUARIO
@BUSCAR NVARCHAR(20)
AS
SELECT * FROM USUARIO
WHERE USUARIO LIKE @BUSCAR + '%'

-- PROCEDIMIENTO ALMACENADO INSERTAR USUARIO

CREATE PROC SP_INSERTARUSUARIO
@USUARIO NVARCHAR(15),
@CONTRASEÑA NVARCHAR(100),
@IDROL INT,
@IDEMPLEADO INT
AS
INSERT INTO USUARIO VALUES (@USUARIO, @CONTRASEÑA,@IDROL,@IDEMPLEADO)

-- PROCEDIMIENTO ALMACENADO EDITAR USUARIO

CREATE PROC SP_EDITARUSUARIO
@IDUSUARIO INT,
@USUARIO NVARCHAR(15),
@CONTRASEÑA NVARCHAR(100),
@IDROL INT,
@IDEMPLEADO INT
AS
UPDATE USUARIO SET USUARIO = @USUARIO, CONTRASEÑA = @CONTRASEÑA, IDROL=@IDROL, IDEMPLEADO = @IDEMPLEADO
WHERE IDUSUARIO = @IDUSUARIO

-- PROCEDIMIENTO ALMACENADO ELIMINAR USUARIO

CREATE PROC SP_ELIMINARUSUARIO
@IDUSUARIO INT
AS
DELETE USUARIO
WHERE IDUSUARIO = @IDUSUARIO

--------------------------------------------------------- STOREPROCEDURES CLIENTE ---------------------------------------------------------


-- PROCEDIMIENTO ALMACENADO BUSCAR CLIENTE

CREATE PROC SP_BUSCARCLIENTE
@BUSCAR NVARCHAR(20)
AS
SELECT * FROM CLIENTE
WHERE NOMBRE LIKE @BUSCAR + '%'

-- PROCEDIMIENTO ALMACENADO INSERTAR CLIENTE



-- PROCEDIMIENTO ALMACENADO EDITAR CLIENTE


-- PROCEDIMIENTO ALMACENADO ELIMINAR CLIENTE

CREATE PROC SP_ELIMINARCLIENTE
@IDCLIENTE INT
AS
DELETE CLIENTE
WHERE IDCLIENTE = @IDCLIENTE

--------------------------------------------------------- STOREPROCEDURES VENTA ---------------------------------------------------------

-- PROCEDIMIENTO ALMACENADO BUSCAR VENTA

CREATE PROC SP_BUSCARVENTA
@BUSCAR NVARCHAR(20)
AS
SELECT * FROM VENTA
WHERE IDVENTA LIKE @BUSCAR + '%'

-- PROCEDIMIENTO ALMACENADO INSERTAR VENTA



-- PROCEDIMIENTO ALMACENADO EDITAR VENTA


-- PROCEDIMIENTO ALMACENADO ELIMINAR VENTA

CREATE PROC SP_ELIMINARVENTA
@IDVENTA INT
AS
DELETE VENTA
WHERE IDVENTA = @IDVENTA

--------------------------------------------------------- STOREPROCEDURES DETALLE_VENTA ---------------------------------------------------------


-- PROCEDIMIENTO ALMACENADO BUSCAR DETALLE_VENTA

CREATE PROC SP_BUSCARDETALLE_VENTA
@BUSCAR NVARCHAR(20)
AS
SELECT * FROM DETALLE_VENTA
WHERE IDDETALLEVENTA LIKE @BUSCAR + '%'

-- PROCEDIMIENTO ALMACENADO INSERTAR DETALLE_VENTA


-- PROCEDIMIENTO ALMACENADO EDITAR DETALLE_VENTA



-- PROCEDIMIENTO ALMACENADO ELIMINAR DETALLE_VENTA

CREATE PROC SP_ELIMINARDETALLE_VENTA
@IDDETALLEVENTA INT
AS
DELETE DETALLE_VENTA
WHERE IDDETALLEVENTA = @IDDETALLEVENTA

--------------------------------------------------------- STOREPROCEDURES CONTROLDATOS ---------------------------------------------------------

CREATE PROC SP_CONTROLDATOS
as
SELECT sum(TOTAL) as ToVentas from VENTA 
SELECT COUNT(IDPRODUCTO) as CantProducto from PRODUCTO 
SELECT COUNT(IDCATEGORIA)as Cant from CATEGORIA 
SELECT COUNT(IDMARCA) as CantMarcas from MARCA 
SELECT COUNT(IDEMPLEADO)as Cantempleado from EMPLEADO
SELECT COUNT(IDCLIENTE) as CantCliente from CLIENTE
go

--------------------------------------------------------- STOREPROCEDURES PRODFAVORITOS ---------------------------------------------------------
CREATE PROC SP_PRODFAVORITOS
as
SELECT  C.NOMBRE +' '+ M.NOMBRE +' '+ P.PRODUCTO as PRODUCTOS, COUNT(DV.IDPRODUCTO)as Procfav from Detalle_Venta as DV
inner join PRODUCTO as P on P.IDPRODUCTO = DV.IDPRODUCTO 
inner join CATEGORIA as C on C.IDCATEGORIA = P.IDCATEGORIA
inner join MARCA as M on M.IDMARCA = P.IDMARCA
group by DV.IDPRODUCTO, C.NOMBRE, M.NOMBRE,P.PRODUCTO
order by COUNT(2) desc
go


--------------------------------------------------------- STOREPROCEDURES PRODCATEGORIA ---------------------------------------------------------
CREATE PROC SP_PRODCATEGORIA
as
SELECT C.NOMBRE ,COUNT(P.IDCATEGORIA)as CANT
from PRODUCTO as P
inner join CATEGORIA as C on C.IDCATEGORIA = P.IDCATEGORIA
group by P.IDCATEGORIA, C.NOMBRE
order by COUNT(2) desc
go