USE SISTEMA_MARANATHA

--------------------------------------------------------- STOREPROCEDURES CATEGORIA ---------------------------------------------------------

-- PROCEDIMIENTO ALMACENADO BUSCAR CATEGORIA

CREATE PROC SP_BUSCARCATEGORIA
@BUSCAR NVARCHAR(20)
AS
SELECT * FROM CATEGORIA
WHERE NOMBRE LIKE @BUSCAR + '%'

-- PROCEDIMIENTO ALMACENADO BUSCAR CATEGORIA POR ID

CREATE PROC SP_BUSCARCATEGORIAXID
@ID INT
AS
SELECT * FROM CATEGORIA
WHERE IDCATEGORIA = @ID

-- PROCEDIMIENTO ALMACENADO INSERTAR CATEGORIA

CREATE PROC SP_INSERTARCATEGORIA
@NOMBRE NVARCHAR(20),
@DESCRIPCION NVARCHAR(256),
@PORCIENTO_VENTA DECIMAL (8,2),
@PORCIENTO_DESCUENTO DECIMAL (8,2)
AS
INSERT INTO CATEGORIA VALUES (@NOMBRE, @DESCRIPCION,@PORCIENTO_VENTA,@PORCIENTO_DESCUENTO)

-- PROCEDIMIENTO ALMACENADO EDITAR CATEGORIA

CREATE PROC SP_EDITARCATEGORIA
@IDCATEGORIA INT,
@NOMBRE NVARCHAR(30),
@DESCRIPCION NVARCHAR(256),
@PORCIENTO_VENTA DECIMAL (8,2),
@PORCIENTO_DESCUENTO DECIMAL (8,2)
AS
UPDATE CATEGORIA SET NOMBRE = @NOMBRE, DESCRIPCION = @DESCRIPCION, PORCIENTO_VENTA = @PORCIENTO_VENTA,PORCIENTO_DESCUENTO = @PORCIENTO_DESCUENTO
WHERE IDCATEGORIA = @IDCATEGORIA

-- PROCEDIMIENTO ALMACENADO ELIMINAR CATEGORIA

CREATE PROC SP_ELIMINARCATEGORIA
@IDCATEGORIA INT
AS
DELETE CATEGORIA
WHERE IDCATEGORIA = @IDCATEGORIA

--------------------------------------------------------- STOREPROCEDURES MARCAS ---------------------------------------------------------

-- PROCEDIMIENTO ALMACENADO BUSCAR MARCA

CREATE PROC SP_BUSCARMARCA
@BUSCAR NVARCHAR(20)
AS
SELECT * FROM MARCA
WHERE NOMBRE LIKE @BUSCAR + '%'

-- PROCEDIMIENTO ALMACENADO INSERTAR MARCA

CREATE PROC SP_INSERTARMARCA
@NOMBRE NVARCHAR(20),
@DESCRIPCION NVARCHAR(256)
AS
INSERT INTO MARCA VALUES (@NOMBRE, @DESCRIPCION)

-- PROCEDIMIENTO ALMACENADO EDITAR MARCA

CREATE PROC SP_EDITARMARCA
@IDMARCA INT,
@NOMBRE NVARCHAR(30),
@DESCRIPCION NVARCHAR(256)
AS
UPDATE MARCA SET NOMBRE = @NOMBRE, DESCRIPCION = @DESCRIPCION
WHERE IDMARCA = @IDMARCA

-- PROCEDIMIENTO ALMACENADO ELIMINAR CATEGORIA

CREATE PROC SP_ELIMINARMARCA
@IDMARCA INT
AS
DELETE MARCA
WHERE IDMARCA = @IDMARCA

--------------------------------------------------------- STOREPROCEDURES PRODUCTOS ---------------------------------------------------------
	
--- PROCEDIMIENTO ALMACENADO PARA LISTAR PRODUCTO COMBO
CREATE PROC SP_LISTARPRODUC
AS
SELECT * FROM PRODUCTOS 
	

-- PROCEDIMIENTO ALMACENADO LISTAR PRODUCTOS

CREATE PROC SP_LISTARPRODUCTOS
AS
SELECT TOP 100
PRODUCTOS.IDPRODUCTO,
PRODUCTOS.CODIGO,
PRODUCTOS.PRODUCTO,
PRODUCTOS.IDCATEGORIA,
CATEGORIA.NOMBRE AS CATEGORIA,
PRODUCTOS.IDMARCA,
MARCA.NOMBRE AS MARCA,
PRODUCTOS.PRECIO_COMPRA,
PRODUCTOS.PRECIO_VENTA,
PRODUCTOS.STOCK
FROM PRODUCTOS
INNER JOIN CATEGORIA ON PRODUCTOS.IDCATEGORIA = CATEGORIA.IDCATEGORIA
INNER JOIN MARCA ON PRODUCTOS.IDMARCA = MARCA.IDMARCA
ORDER BY IDPRODUCTO ASC

-- PROCEDIMIENTO ALMACENADO BUSCAR PRODUCTOS

CREATE PROC SP_BUSCARPRODUCTOS
@BUSCAR NVARCHAR(20)
AS
SELECT TOP 100
PRODUCTOS.IDPRODUCTO,
PRODUCTOS.CODIGO,
PRODUCTOS.PRODUCTO,
PRODUCTOS.IDCATEGORIA,
CATEGORIA.NOMBRE AS CATEGORIA,
PRODUCTOS.IDMARCA,
MARCA.NOMBRE AS MARCA,
PRODUCTOS.PRECIO_COMPRA,
PRODUCTOS.PRECIO_VENTA,
PRODUCTOS.STOCK
FROM PRODUCTOS
INNER JOIN CATEGORIA ON PRODUCTOS.IDCATEGORIA = CATEGORIA.IDCATEGORIA
INNER JOIN MARCA ON PRODUCTOS.IDMARCA = MARCA.IDMARCA
WHERE PRODUCTO LIKE @BUSCAR + '%'
ORDER BY IDPRODUCTO ASC

-- PROCEDIMIENTO ALMACENADO INSERTAR PRODUCTOS

CREATE PROC SP_INSERTARPRODUCTOS
@PRODUCTO NVARCHAR(50),
@PRECIO_COMPRA DECIMAL (18,2),
@PRECIO_VENTA DECIMAL (18,2),
@STOCK INT,
@IDCATEGORIA INT,
@IDMARCA INT
AS
INSERT INTO PRODUCTOS VALUES (@PRODUCTO, @PRECIO_COMPRA, @PRECIO_VENTA, @STOCK, @IDCATEGORIA, @IDMARCA)

-- PROCEDIMIENTO ALMACENADO EDITAR PRODUCTO

CREATE PROC SP_EDITARPRODUCTOS
@IDPRODUCTO INT,
@PRODUCTO NVARCHAR(50),
@PRECIO_COMPRA DECIMAL (18,2),
@PRECIO_VENTA DECIMAL (18,2),
@STOCK INT,
@IDCATEGORIA INT,
@IDMARCA INT
AS
UPDATE PRODUCTOS SET PRODUCTO = @PRODUCTO, PRECIO_COMPRA = @PRECIO_COMPRA, PRECIO_VENTA = @PRECIO_VENTA, STOCK = @STOCK, IDCATEGORIA = @IDCATEGORIA, IDMARCA = @IDMARCA
WHERE IDPRODUCTO = @IDPRODUCTO

-- PROCEDIMIENTO ALMACENADO ELIMINAR PRODUCTO

CREATE PROC SP_ELIMINARPRODUCTOS
@IDPRODUCTO INT
AS
DELETE PRODUCTOS 
WHERE IDPRODUCTO = @IDPRODUCTO

-- PROCEDIMIENTO ALMACENADO CUENTAS TOTALES

CREATE PROC SP_TOTALESPRODUCT
@TOTALCATEGORIA INT OUTPUT,
@TOTALMARCA INT OUTPUT,
@TOTALPRODUCTO INT OUTPUT,
@SUMSTOCK INT OUTPUT
AS
SET @TOTALCATEGORIA = (SELECT COUNT(IDCATEGORIA) AS CATEGORIAS FROM CATEGORIA)
SET @TOTALMARCA = (SELECT COUNT(IDMARCA) AS MARCA FROM MARCA)
SET @TOTALPRODUCTO = (SELECT COUNT(IDPRODUCTO) AS PRODUCTO FROM PRODUCTOS)
SET @SUMSTOCK = (SELECT SUM(STOCK) AS TOTALPRODUCTOS FROM PRODUCTOS)


--------------------------------------------------------- STOREPROCEDURES ROL ---------------------------------------------------------


-- PROCEDIMIENTO ALMACENADO BUSCAR ROL

CREATE PROC SP_BUSCAR_ROL
@BUSCAR NVARCHAR(20)
AS
SELECT * FROM ROL
WHERE ROL LIKE @BUSCAR + '%'


--------------------------------------------------------- STOREPROCEDURES USUARIO ---------------------------------------------------------


-- PROCEDIMIENTO ALMACENADO BUSCAR USUARIO

CREATE PROC SP_BUSCAR_USUARIO
@BUSCAR NVARCHAR(20)
AS
SELECT * FROM USUARIO
WHERE USUARIO LIKE @BUSCAR + '%'


-- PROCEDIMIENTO ALMACENADO INSERTAR USUARIO

CREATE PROC SP_INSERTAR_USUARIO
@USUARIO NVARCHAR(15),
@CONTRASEÑA NVARCHAR(100),
@NOMBRE NVARCHAR(40),
@APELLIDO NVARCHAR(40),
@IDROL INT
AS
INSERT INTO USUARIO VALUES (@USUARIO, @CONTRASEÑA,@NOMBRE ,@APELLIDO,@IDROL)

INSERT INTO USUARIO VALUES ('moiszr', 'moises1234','Moises' ,'Nuñez del Rosario',1)
-- PROCEDIMIENTO ALMACENADO EDITAR USUARIO

CREATE PROC SP_EDITAR_USUARIO
@IDUSUARIO INT,
@USUARIO NVARCHAR(15),
@CONTRASEÑA NVARCHAR(100),
@NOMBRE NVARCHAR(40),
@APELLIDO NVARCHAR(40),
@IDROL INT
AS
UPDATE USUARIO SET USUARIO = @USUARIO, CONTRASEÑA = @CONTRASEÑA, IDROL=@IDROL, NOMBRE = @NOMBRE, APELLIDO = @APELLIDO
WHERE IDUSUARIO = @IDUSUARIO

-- PROCEDIMIENTO ALMACENADO ELIMINAR USUARIO

CREATE PROC SP_ELIMINAR_USUARIO
@IDUSUARIO INT
AS
DELETE USUARIO
WHERE IDUSUARIO = @IDUSUARIO

-----PROCEDIMIENTO ALMACENADO listar usuarios
CREATE PROC SP_LISTARUSUARIO
AS
SELECT TOP 100
USUARIO.IDUSUARIO,
USUARIO.CODIGO,
USUARIO.NOMBRE,
USUARIO.APELLIDO,
USUARIO.USUARIO,
USUARIO.CONTRASEÑA,
ROL.ROL AS ROL
FROM USUARIO
INNER JOIN ROL ON USUARIO.IDROL = ROL.IDROL



----PROCEDIMIENTO ALMACENADO LOGIN
CREATE PROC SP_LOGIN
@USUARIO NVARCHAR(100),
@CONTRASEÑA NVARCHAR(15)
AS
SELECT
USUARIO.IDUSUARIO,
USUARIO.CODIGO,
USUARIO.NOMBRE,
USUARIO.APELLIDO,
USUARIO.USUARIO,
USUARIO.CONTRASEÑA,
ROL.ROL AS ROL
FROM USUARIO
INNER JOIN ROL ON USUARIO.IDROL = ROL.IDROL
WHERE USUARIO = @USUARIO and CONTRASEÑA = @CONTRASEÑA


--------------------------------------------------------- STOREPROCEDURES CLIENTE ---------------------------------------------------------
	

	

-- PROCEDIMIENTO ALMACENADO BUSCAR CLIENTE

CREATE PROC SP_BUSCAR_CLIENTE
@BUSCAR NVARCHAR(20)
AS
SELECT * FROM CLIENTE
WHERE NOMBRE LIKE @BUSCAR + '%'

-- PROCEDIMIENTO ALMACENADO INSERTAR CLIENTE

CREATE PROC SP_INSERTAR_CLIENTE

@NOMBRE NVARCHAR (30),
@APELLIDO NVARCHAR(60),
@CEDULA VARCHAR(15),
@APODO NVARCHAR(50) ,
@TELEFONO1 VARCHAR(10) ,
@TELEFONO2 VARCHAR(10) ,
@CELULAR VARCHAR(10),
@DIRECCION NVARCHAR(256),
@CASA VARCHAR(50),
@LUGARDETRABAJO NVARCHAR(60),
@TELEFONOTRABAJO VARCHAR(10),
@NOMBRESUPERIOR NVARCHAR(70),
@TELEFONOSUPERIOR VARCHAR(10),
@TIEMPOLABORANDO VARCHAR(10),
@SALARIOMENSUAL DECIMAL(18,2),
@NOMBRECONYUGUE NVARCHAR(70),
@TELEFONOCONYUGUE VARCHAR(10),
@TRABAJOCONYUGUE NVARCHAR(60),
@TELEFONOTRABAJOCONYUGUE VARCHAR(10),
@NOMBRESUPERIORCONYUGUE NVARCHAR(70),
@TELEFONOSUPERIORCONYUGUE VARCHAR(10),
@TIEMPOLABORANDOCONYUGUE VARCHAR(10),
@SALARIOMENSUALCONYUGUE DECIMAL(18,2),
@NOMBRE_APELLIDO_TELEFONO_REFERENCIA1 NVARCHAR(100),
@NOMBRE_APELLIDO_TELEFONO_REFERENCIA2 NVARCHAR(100),
@NOMBRE_APELLIDO_TELEFONO_REFERENCIA3 NVARCHAR(100),
@NOMBRE_APELLIDO_TELEFONO_FAMILIAR1 NVARCHAR(100),
@NOMBRE_APELLIDO_TELEFONO_FAMILIAR2 NVARCHAR(100),
@NOMBRE_APELLIDO_TELEFONO_FAMILIAR3 NVARCHAR(100) 

AS
INSERT INTO CLIENTE VALUES (@NOMBRE, @APELLIDO, @CEDULA, @APODO, @TELEFONO1, @TELEFONO2, @CELULAR, @DIRECCION, @CASA,
							@LUGARDETRABAJO, @TELEFONOTRABAJO, @NOMBRESUPERIOR, @TELEFONOSUPERIOR, @TIEMPOLABORANDO,
							@SALARIOMENSUAL, @NOMBRECONYUGUE, @TELEFONOCONYUGUE, @TRABAJOCONYUGUE,
							@TELEFONOTRABAJOCONYUGUE, @NOMBRESUPERIORCONYUGUE, @TELEFONOSUPERIORCONYUGUE, @TIEMPOLABORANDOCONYUGUE,
							@SALARIOMENSUALCONYUGUE, @NOMBRE_APELLIDO_TELEFONO_REFERENCIA1, @NOMBRE_APELLIDO_TELEFONO_REFERENCIA2,
							@NOMBRE_APELLIDO_TELEFONO_REFERENCIA3, @NOMBRE_APELLIDO_TELEFONO_FAMILIAR1,
							@NOMBRE_APELLIDO_TELEFONO_FAMILIAR2, @NOMBRE_APELLIDO_TELEFONO_FAMILIAR3)

-- PROCEDIMIENTO ALMACENADO EDITAR CLIENTE
CREATE PROC SP_EDITAR_CLIENTE
@IDCLIENTE INT ,
@NOMBRE NVARCHAR (30),
@APELLIDO NVARCHAR(60),
@APODO NVARCHAR(50) ,
@TELEFONO1 VARCHAR(10) ,
@TELEFONO2 VARCHAR(10) ,
@CELULAR VARCHAR(10),
@DIRECCION NVARCHAR(256),
@CASA VARCHAR(50),
@LUGARDETRABAJO NVARCHAR(60),
@TELEFONOTRABAJO VARCHAR(10),
@NOMBRESUPERIOR NVARCHAR(70),
@TELEFONOSUPERIOR VARCHAR(10),
@TIEMPOLABORANDO VARCHAR(10),
@SALARIOMENSUAL DECIMAL(18,2),
@NOMBRECONYUGUE NVARCHAR(70),
@TELEFONOCONYUGUE VARCHAR(10),
@TRABAJOCONYUGUE NVARCHAR(60),
@TELEFONOTRABAJOCONYUGUE VARCHAR(10),
@NOMBRESUPERIORCONYUGUE NVARCHAR(70),
@TELEFONOSUPERIORCONYUGUE VARCHAR(10),
@TIEMPOLABORANDOCONYUGUE VARCHAR(10),
@SALARIOMENSUALCONYUGUE DECIMAL(18,2),
@NOMBRE_APELLIDO_TELEFONO_REFERENCIA1 NVARCHAR(100),
@NOMBRE_APELLIDO_TELEFONO_REFERENCIA2 NVARCHAR(100),
@NOMBRE_APELLIDO_TELEFONO_REFERENCIA3 NVARCHAR(100),
@NOMBRE_APELLIDO_TELEFONO_FAMILIAR1 NVARCHAR(100),
@NOMBRE_APELLIDO_TELEFONO_FAMILIAR2 NVARCHAR(100),
@NOMBRE_APELLIDO_TELEFONO_FAMILIAR3 NVARCHAR(100) 

AS
UPDATE CLIENTE SET NOMBRE = @NOMBRE, APELLIDO = @APELLIDO, APODO = @APODO,TELEFONO1 = @TELEFONO1,TELEFONO2 =  @TELEFONO2, CELULAR = @CELULAR, 
					DIRECCION =  @DIRECCION, CASA = @CASA, LUGARDETRABAJO = @LUGARDETRABAJO, TELEFONOTRABAJO = @TELEFONOTRABAJO, 
					NOMBRESUPERIOR = @NOMBRESUPERIOR, TELEFONOSUPERIOR = @TELEFONOSUPERIOR, TIEMPOLABORANDO = @TIEMPOLABORANDO,
					SALARIOMENSUAL = @SALARIOMENSUAL, NOMBRECONYUGUE = @NOMBRECONYUGUE, TELEFONOCONYUGUE = @TELEFONOCONYUGUE, TRABAJOCONYUGUE = @TRABAJOCONYUGUE,
					TELEFONOTRABAJOCONYUGUE = @TELEFONOTRABAJOCONYUGUE, NOMBRESUPERIORCONYUGUE = @NOMBRESUPERIORCONYUGUE, 
					TELEFONOSUPERIORCONYUGUE = @TELEFONOSUPERIORCONYUGUE,TIEMPOLABORANDOCONYUGUE = @TIEMPOLABORANDOCONYUGUE, SALARIOMENSUALCONYUGUE = @SALARIOMENSUALCONYUGUE, 
					NOMBRE_APELLIDO_TELEFONO_REFERENCIA1 = @NOMBRE_APELLIDO_TELEFONO_REFERENCIA1, NOMBRE_APELLIDO_TELEFONO_REFERENCIA2 = @NOMBRE_APELLIDO_TELEFONO_REFERENCIA2,
					NOMBRE_APELLIDO_TELEFONO_REFERENCIA3 = @NOMBRE_APELLIDO_TELEFONO_REFERENCIA3, NOMBRE_APELLIDO_TELEFONO_FAMILIAR1 = @NOMBRE_APELLIDO_TELEFONO_FAMILIAR1,
					NOMBRE_APELLIDO_TELEFONO_FAMILIAR2 = @NOMBRE_APELLIDO_TELEFONO_FAMILIAR2, NOMBRE_APELLIDO_TELEFONO_FAMILIAR3 = @NOMBRE_APELLIDO_TELEFONO_FAMILIAR3

					WHERE IDCLIENTE = @IDCLIENTE


-- PROCEDIMIENTO ALMACENADO ELIMINAR CLIENTE

CREATE PROC SP_ELIMINAR_CLIENTE
@IDCLIENTE INT
AS
DELETE CLIENTE
WHERE IDCLIENTE = @IDCLIENTE

-- PROCEDIMIENTO ALMACENADO LISTAR CLIENTE

CREATE PROC SP_LISTARCLIENTE
AS
SELECT * FROM CLIENTE

-- PROCEDIMIENTO ALMACENADO LISTAR CLIENTE PARA COMBO BOX

CREATE PROC SP_LISTARCLIENTECMB
AS
SELECT IDCLIENTE, NOMBRE + ' ' + APELLIDO AS 'CLIENTE' FROM CLIENTE

--------------------------------------------------------- STOREPROCEDURES VENTAS ---------------------------------------------------------

-- PROCEDIMIENTO ALMACENADO BUSCAR VENTAS
CREATE PROC SP_BUSCAR_VENTA(
@BUSCAR INT
)
AS
SELECT * FROM VENTA WHERE IDVENTA = @BUSCAR

-- PROCEDIMIENTO ALMACENADO MOSTRAR VENTAS --

CREATE PROC SP_MOSTRAR_VENTA
AS
SELECT IDVENTA, v.CODIGO, NOMBRE_CLIENTE, u.NOMBRE + ' ' + u.APELLIDO as USUARIO, FECHA, TOTAL FROM VENTA v
INNER JOIN USUARIO u ON v.IDUSUARIO = u.IDUSUARIO
ORDER BY IDVENTA DESC

-- PROCEDIMIENTO ALMACENADO INSERTAR VENTAS

CREATE PROC SP_INSERTAR_VENTA(
	@FECHA DATE,
	@TOTAL DECIMAL(18,2),
	@NOMBRE_CLIENTE Nvarchar(60),
	@IDUSUARIO INT,
	@IDGARANTE INT
)
AS
INSERT INTO VENTA VALUES(@FECHA, @TOTAL, @NOMBRE_CLIENTE, @IDUSUARIO, @IDGARANTE)


--------PROCEDIMIENTO OBTENER ID VENTAS

CREATE PROC SP_OBTENER_ID_VENTA
AS
SELECT MAX(IDVENTA) AS ID FROM VENTA


--------------------------------------------------------- STOREPROCEDURES DETALLEVENTA ---------------------------------------------------------
------------------------------MOSTRAR DETALLEVENTA
CREATE PROC SP_LISTAR_DETALLE_VENTA(
@ID INT
)
AS
SELECT d.CODIGO, v.CODIGO, p.PRODUCTO, PRECIOVENTA, CANTIDAD, DESCUENTO, SUBTOTAL  FROM DETALLE_VENTA d
INNER JOIN PRODUCTOS p ON d.IDPRODUCTO = p.IDPRODUCTO
INNER JOIN VENTA v ON d.IDVENTA = v.IDVENTA
WHERE d.IDVENTA = @ID

-----------------------------CREATE DETALLEVENTA--------
CREATE PROC SP_DETALLE_VENTA(
	@PRECIOVENTA DECIMAL (18,2),
	@CANTIDAD INT,
	@DESCUENTO DECIMAL(18,2),
	@SUBTOTAL DECIMAL(18,2),
	@IDVENTA INT,
	@IDPRODUCTO INT
	)
	AS
	INSERT INTO DETALLE_VENTA VALUES(@PRECIOVENTA, @CANTIDAD, @DESCUENTO, @SUBTOTAL, @IDVENTA, @IDPRODUCTO)

----PROCEDIMIENTO ALMACENADO BUSCAR DATA FACTURA
CREATE PROC SP_DATA_FACTURA(
@ID INT)
AS
SELECT * FROM PRODUCTOS WHERE IDPRODUCTO = @ID
--------------------------------------------------------- STOREPROCEDURES PAGOS ---------------------------------------------------------

-- PROCEDIMIENTO ALMACENADO BUSCAR PAGOS
CREATE PROC SP_BUSCAR_PAGOS(
@ID INT
)
AS
SELECT * FROM PAGOS WHERE IDPAGOS = @ID

-- PROCEDIMIENTO ALMACENADO LISTAR PAGOS
CREATE PROC SP_LISTAR_PAGOS
AS
SELECT TOP 100 IDPAGOS, P.CODIGO, P.ESTADO, V.CODIGO, C.NOMBRE + ' ' + C.APELLIDO AS CLIENTE, C.CEDULA, G.NOMBRE + ' ' + G.APELLIDO AS GARANTE, P.IDVENTA, P.IDCLIENTE, P.IDGARANTE FROM PAGOS P
INNER JOIN CLIENTE C ON P.IDCLIENTE = C.IDCLIENTE
INNER JOIN GARANTE G ON P.IDGARANTE = G.IDGARANTE
INNER JOIN VENTA V ON P.IDVENTA = V.IDVENTA
ORDER BY IDPAGOS DESC

-- PROCEDIMIENTO ALMACENADO BUSCAR ID PAGOS
CREATE PROC SP_OBTENER_ID_PAGOS
AS
SELECT MAX(IDPAGOS) AS ID FROM PAGOS


-- PROCEDIMIENTO ALMACENADO INSERTAR PAGOS
CREATE PROC SP_INSERTAR_PAGOS(
	@ESTADO VARCHAR(20),
	@IDVENTA INT,
	@IDCLIENTE INT,
	@IDGARANTE INT  
)
AS
INSERT INTO PAGOS VALUES (@ESTADO, @IDVENTA, @IDCLIENTE, @IDGARANTE)


--------------------------------------------------------- STOREPROCEDURES GARANTE ---------------------------------------------------------

-- PROCEDIMIENTO ALMACENADO BUSCAR GARANTE
CREATE PROC SP_BUSCAR_GARANTE(
@ID INT
)
AS
SELECT * FROM GARANTE WHERE IDGARANTE = @ID

-- PROCEDIMIENTO ALMACENADO OBTENER ID
CREATE PROC SP_OBTENER_ID_GARANTE
AS
SELECT MAX(IDGARANTE) AS ID FROM GARANTE
select *from USUARIO


-- PROCEDIMIENTO ALMACENADO INSERTAR GARANTE
CREATE PROC SP_INSERTAR_GARANTE
(
	@NOMBRE NVARCHAR(30),
	@APELLIDO NVARCHAR(60),
	@CEDULA NVARCHAR(15),
	@TELEFONO1 VARCHAR(10),
	@CELULAR VARCHAR(10),
	@DIRECCION NVARCHAR(256),
	@TRABAJO NVARCHAR(70),
	@SUELDO DECIMAL (18,2) 
)
AS
INSERT INTO GARANTE VALUES (@NOMBRE, @APELLIDO, @CEDULA, @TELEFONO1, @CELULAR, @DIRECCION, @TRABAJO, @SUELDO)

--------------------------------------------------------- STOREPROCEDURES CREDITO ---------------------------------------------------------

-- PROCEDIMIENTO ALMACENADO BUSCAR CREDITO
CREATE PROC SP_LISTAR_CREDITO(
@ID INT
)
AS
SELECT * FROM CREDITO WHERE IDPAGOS = @ID

-- PROCEDIMIENTO ALMACENADO INSERTAR CREDITO
CREATE PROC SP_INSERTAR_CREDITO
(
	@NO_PAGO INT,
	@FECHA DATE,
	@CUOTAS DECIMAL (18,2),
	@CAPITAL DECIMAL(18,2),
	@INTERES DECIMAL(18,2),
	@MORA DECIMAL(18,2),
	@IDPAGO INT
)
AS
INSERT INTO CREDITO (NO_PAGO, FECHA, CUOTAS, CAPITAL, INTERES, MORA, ESTADO, IDPAGOS)
VALUES (@NO_PAGO, @FECHA, @CUOTAS, @CAPITAL, @INTERES, @MORA, 'NO PAGO', @IDPAGO)

-- PROCEDIMIENTO ALMACENADO EDITAR CREDITO
CREATE PROC SP_EDIT_CREDITO(
@IDCREDIO INT,
@FECHA DATE,
@TOTAL_VENTA DECIMAL(18,2),
@INTERES DECIMAL (8,2),
@TIEMPO INT,
@CUOTAS_PAGADAS INT,
@CUOTA DECIMAL(18,2),
@TOTAL_PAGADO DECIMAL(18,2),
@TOTAL_PAGAR DECIMAL(18,2),
@IDVENTA INT,
@IDCLIENTE INT
)
AS
UPDATE CREDITO SET FECHA = @FECHA, TOTAL_VENTA = @TOTAL_VENTA, INTERES = @INTERES, TIEMPO = @TIEMPO, 
					CUOTAS_PAGADAS = @CUOTAS_PAGADAS, CUOTA = @CUOTA, TOTAL_PAGADO =  @TOTAL_PAGADO,  
					TOTAL_PAGAR = @TOTAL_PAGAR, IDVENTA = @IDVENTA, IDCLIENTE = @IDCLIENTE

-- PROCEDIMIENTO ALMACENADO ELIMINAR CREDITO
CREATE PROC SP_ELIMINAR_CREDITO
@IDCREDIO INT
AS
DELETE CREDITO
WHERE IDCREDIO = @IDCREDIO

--------------------------------------------------------- STOREPROCEDURES CONTROLDATOS ---------------------------------------------------------


CREATE PROC SP_CONTROLDATOS
as
SELECT sum(TOTAL) as ToVentas from VENTA 
SELECT COUNT(IDPRODUCTO) as CantProducto from PRODUCTO 
SELECT COUNT(IDCATEGORIA)as Cant from CATEGORIA 
SELECT COUNT(IDMARCA) as CantMarcas from MARCA 
SELECT COUNT(IDEMPLEADO)as Cantempleado from EMPLEADO
SELECT COUNT(IDCLIENTE) as CantCliente from CLIENTE
go

--------------------------------------------------------- STOREPROCEDURES PRODFAVORITOS ---------------------------------------------------------
CREATE PROC SP_PRODFAVORITOS
as
SELECT  C.NOMBRE +' '+ M.NOMBRE +' '+ P.PRODUCTO as PRODUCTOS, COUNT(DV.IDPRODUCTO)as Procfav from Detalle_Venta as DV
inner join PRODUCTO as P on P.IDPRODUCTO = DV.IDPRODUCTO 
inner join CATEGORIA as C on C.IDCATEGORIA = P.IDCATEGORIA
inner join MARCA as M on M.IDMARCA = P.IDMARCA
group by DV.IDPRODUCTO, C.NOMBRE, M.NOMBRE,P.PRODUCTO
order by COUNT(2) desc
go


--------------------------------------------------------- STOREPROCEDURES PRODCATEGORIA ---------------------------------------------------------
CREATE PROC SP_PRODCATEGORIA
as
SELECT C.NOMBRE ,COUNT(P.IDCATEGORIA)as CANT
from PRODUCTO as P
inner join CATEGORIA as C on C.IDCATEGORIA = P.IDCATEGORIA
group by P.IDCATEGORIA, C.NOMBRE
order by COUNT(2) desc
go



Select *from DETALLE_VENTA where IDVENTA = 28
select *from PAGOS
select *from CREDITO where IDPAGOS = 6